version: '2'
services:
  ansible:
    image: ansible-image7
    hostname: ansible
    tty: true
    container_name: ansible
    networks: 
      - allow_ssh
    ports:
      - 127.0.0.1:2221:22
  
  host1:
    image: host-centos
    hostname: host1_centos
    tty: true
    container_name: host_centos
    networks: 
      - allow_ssh
    ports:
      - 127.0.0.1:2222:22

  host2:
    image: host-ubuntu
    hostname: host2_ubuntu
    tty: true
    container_name: host_ubuntu
    networks: 
      - allow_ssh
    ports:
      - 127.0.0.1:2223:22

networks:
  allow_ssh:
